global:
  env: dev
  components:
    udt-ui:
      version: 127f9c89e4d52a3d5ecaed1566da2d0eb816ff9f

deployment:
  image:
    tag: 127f9c89e4d52a3d5ecaed1566da2d0eb816ff9f

s3ingress:
  namespace: kargophil
