global:
  env: dev
  components:
    udt-ui:
      version: ""

deployment:
  image:
    tag: ""
  ports:
    http: 9090
  resources:
    requests:
      memory: 200Mi
      cpu: "0.5"

s3ingress:
  namespace: kargophil
