global:
  env: dev
  components:
    udt-ui:
      version: da3d9cc88faec809a2f9900fb568595b51d30d55

deployment:
  image:
    tag: da3d9cc88faec809a2f9900fb568595b51d30d55
  ports:
    http: 9090
  resources:
    requests:
      memory: 200Mi
      cpu: "0.5"

s3ingress:
  namespace: kargophil
